docker push epinux/metsis-drupal
docker push epinux/metsis-postgres
docker push epinux/metsis-pybasket
docker push epinux/metsis-pydap
docker push epinux/metsis-pywps
docker push epinux/metsis-solr
docker push epinux/metsis-pybasket
docker push epinux/metsis-jupyter
docker push epinux/metsis-pycsw
