version: '3.5'
services:
  solr:
    build:
      context: ./metsis-solr/
      dockerfile: Dockerfile
    container_name: metsis_solr
    image: epinux/metsis-solr
    environment:
      VIRTUAL_HOST: ${SOLR_VIRTUAL_HOST}
      VIRTUAL_PORT: 8983
      NETWORK_ACCESS: internal
      LETSENCRYPT_HOST: ${SOLR_VIRTUAL_HOST}
      LETSENCRYPT_MAIL: ${MY_EMAIL}
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr/data
      - ./volumes/solr/data:/tmp/data
    restart: unless-stopped
    entrypoint:
      - bash
      - "-c"
      - "precreate-core nbs-l1 /opt/solr/server/solr/configsets/myconfig ; precreate-core nbs-l2 /opt/solr/server/solr/configsets/myconfig; precreate-core nbs-thumbnail /opt/solr/server/solr/configsets/myconfig; exec solr -f"

  drupal:
    build:
      context: ./metsis-drupal/
      dockerfile: Dockerfile
    container_name: metsis_drupal
    image: epinux/metsis-drupal
    depends_on:
      - postgres
    ports:
      - "8080:80"
    volumes:
      - drupal_data:/var/www/html
      - ./volumes/drupal/sites/all/modules/metsis_ts_bokeh:/var/www/html/sites/all/modules/metsis_ts_bokeh
    restart: always
    links:
      - fastapi

  fastapi:
    build:
      context: ./metsis-fastapi/
      dockerfile: Dockerfile
    container_name: metsis_fastapi
    image: epinux/metsis-fastapi
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./volumes/fastapi/pybasket/config.yaml:/opt/basket/config.yaml
      - ./volumes/fastapi/pybasket/app:/app

volumes:
  solr_data:
    name: solr_data
  drupal_data:
    name: drupal_data
  pybasket_data:
    name: pybasket_data
