version: '3.5'
services:
  solr:
    build:
      context: ./metsis-solr/
      dockerfile: Dockerfile
    container_name: metsis_solr
    image: epinux/metsis-solr
    environment:
      VIRTUAL_HOST: ${SOLR_VIRTUAL_HOST}
      VIRTUAL_PORT: 8983
      NETWORK_ACCESS: internal
      LETSENCRYPT_HOST: ${SOLR_VIRTUAL_HOST}
      LETSENCRYPT_MAIL: ${MY_EMAIL}
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr/data
      - ./volumes/solr/data:/tmp/data
    restart: unless-stopped
    entrypoint:
      - bash
      - "-c"
      - "precreate-core nbs-l1 /opt/solr/server/solr/configsets/myconfig ; precreate-core nbs-l2 /opt/solr/server/solr/configsets/myconfig; precreate-core nbs-thumbnail /opt/solr/server/solr/configsets/myconfig; exec solr -f"

  pywps:
    build:
      context: ./metsis-pywps/
      dockerfile: Dockerfile
    container_name: metsis_pywps
    image: epinux/metsis-pywps
    ports:
      - "5000:80"
    volumes:
      - ./volumes/pywps/processes:/pywps-flask/processes
      - ./volumes/pywps/data:/pywps-flask/data
      - ./volumes/pywps/outputs:/pywps-flask/outputs
      - ./volumes/pywps/pywps-flask/demo.py:/pywps-flask/demo.py
      - ./volumes/pywps/pywps-flask/wsgi/pywps.wsgi:/pywps-flask/wsgi/pywps.wsgi
      - ./volumes/pywps/pywps-flask/pywps.cfg:/pywps-flask/pywps.cfg
    restart: unless-stopped

  pydap:
    build:
      context: ./metsis-pydap/
      dockerfile: Dockerfile
    container_name: metsis_pydap
    image: epinux/metsis-pydap
    ports:
      - "9999:80"
    volumes:
      - ./volumes/pydap/data:/var/www/sites/pydap/server/data
    restart: unless-stopped


  jupyter:
    build:
      context: ./metsis-jupyter/
      dockerfile: Dockerfile
    container_name: metsis_jupyter
    image: epinux/metsis-jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./volumes/jupyter/notebooks:/home/metsis/work
      - ./volumes/pydap/data/html:/home/metsis/work/html
      - ./volumes/pycsw/sample_data:/home/metsis/work/sample_data
    restart: unless-stopped


  drupal:
    build:
      context: ./metsis-drupal/
      dockerfile: Dockerfile
    container_name: metsis_drupal7
    image: epinux/metsis-drupal7
    depends_on:
      - postgres
    ports:
      - "8080:80"
    #volumes:
    #  - ./volumes/drupal/modules:/var/www/html/modules
    #  - ./volumes/drupal/profiles:/var/www/html/profiles
    #  - ./volumes/drupal/themes:/var/www/html/themes
    #  - ./volumes/drupal/sites:/var/www/html/sites
    #volumes:
    #  - ./volumes/drupal8/modules:/var/www/html/modules
    #  - ./volumes/drupal8/profiles:/var/www/html/profiles
    #  - ./volumes/drupal8/themes:/var/www/html/themes
    #  - ./volumes/drupal8/sites:/var/www/html/sites
    #volumes:
    #  - ./volumes/drupal:/var/www/html
    #volumes:
    #  - drupal8_data:/var/www/html
    volumes:
      - drupal7_data:/var/www/html
    restart: always
    links:
      - fastapi

  postgres:
    build:
      context: ./metsis-postgres/
      dockerfile: Dockerfile
    container_name: metsis_postgres
    image: epinux/metsis-postgres
    restart: always
    hostname: postgres
    environment:
      POSTGRES_INITDB_ARGS: "-E UTF8"
      POSTGRES_DB: drupal_db,csw_db,metsis_test
      POSTGRES_USER: metsis_user
      POSTGRES_PASSWORD: metsis_password
      LANGUAGE: "en_US.UTF-8"
      LANG: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/11
    ports:
      - "5432:5432"

  pycsw:
    build:
      context: ./metsis-pycsw/
      dockerfile: Dockerfile
    container_name: metsis_pycsw
    image: epinux/metsis-pycsw
    ports:
      - "8000:8000"
    environment:
      INDEXDB: "false"
      METADATA: "/home/pycsw/sample_data/xml/adc/XML"
      OUTPUT_ISO: "/home/pycsw/sample_data/iso_xml/adc"
      FIX: "false"
    restart: unless-stopped
    depends_on:
      - "postgres"
    volumes:
      - ./volumes/pycsw/conf/pycsw.cfg:/etc/pycsw/pycsw.cfg
      - ./volumes/pycsw/commands/pycsw_setup.sh:/usr/local/bin/pycsw_setup.sh
      - ./volumes/pycsw/commands/mmd2isofix.py:/usr/local/bin/mmd2isofix.py
      - ./volumes/pycsw/commands/mmd-to-iso.xsl:/usr/local/share/mmd-to-iso.xsl
      - ./volumes/pycsw/xml/test.xml:/home/pycsw/test.xml
      - ./volumes/pycsw/xml/test_fix.xml:/home/pycsw/test_fix.xml
      - ./volumes/pycsw/sample_data:/home/pycsw/sample_data
      - ./volumes/pycsw/conf/.bash_history:/root/.bash_history
    entrypoint:
      - /bin/sh
      - /usr/local/bin/pycsw_setup.sh


  fastapi:
    build:
      context: ./metsis-fastapi/
      dockerfile: Dockerfile
    container_name: metsis_fastapi
    image: epinux/metsis-fastapi
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./volumes/fastapi/pybasket/config.yaml:/opt/basket/config.yaml
      - ./volumes/fastapi/pybasket/app:/app


  hyrax:
    container_name: hyrax
    image: opendap/hyrax:latest
    ports:
      - "9090:8080"
    volumes:
      - ./volumes/pydap/data:/usr/share/hyrax


volumes:
  solr_data:
    name: solr_data
  pywps_data:
    name: pywps_data
  pydap_data:
    name: pydap_data
  postgres_data:
    name: postgres_data
  #drupal8_data:
  #  name: drupal8_data
  drupal7_data:
    name: drupal7_data
  pybasket_data:
    name: pybasket_data
