FROM ubuntu:xenial

ENV DEBIAN_FRONTEND=noninteractive

ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
ENV C_INCLUDE_PATH=/usr/include/gdal

RUN apt-get update && apt-get -y dist-upgrade

MAINTAINER Massimo Di Stefano <massimods@met.no>

RUN apt-get update -y && apt-get install -y  \
	software-properties-common \
	build-essential \
	python3-dev \
	python3-numpy \
	python3-lxml \
	python3-pip \
    python \
    python-pip \
    python-lxml \
    python-gdal \
    libgdal-dev \
    gdal-bin \
    apache2 \
    libapache2-mod-fastcgi \
    libapache2-mod-fcgid \
    python-magic

RUN pip2 install pywps==3.2.6

RUN add-apt-repository -y ppa:met-norway/fimex && apt-get update && apt-get install -y fimex-0.65-bin python3-pyfimex0-0.65 python3-gdal

EXPOSE 80 


CMD ["apachectl", "-D", "FOREGROUND", "-e", "info"]