solr:
  endpoint: "http://host:port/solr/"
archive:
  endpoint: "0.0.0.0"
  scheme: http
  path: ""
  privateKey: ""
  username: ""
  passphrase: ""
  directory: ""
  expiredHours: 48

fimex:
  wpsService: "http://host:port/wps?service=wps&version=1.0.0&request=getcapabilities"

# Mail server. Used for sending emails requested from basket
mail:
  smtp:
    host: smtp.outgoing.server
    port: 0
  from: noreply@outgoing.server
  mime:
    charset: utf-8
  subject: Notification from data center
  body:
    content: "You have ordered the following datasets from {0}:\r\n{1}\r\n"
    uriFailed: \r\nWe are sorry that we were unable to fetch the following datasets:\r\n{0}\r\n
    error: \r\nWe were unable to process your order {0}. \r\nYour reference number is {1}. Please contact our administrator. \r\n
    archiveUrl: "\r\nYour valid data is ready to download at: {0}. This URL will be expire on {1,date,dd-MMM-yyyy}.\r\n"