# =================================================================
#
# Authors: Ricardo Garcia Silva <ricardo.garcia.silva@gmail.com>
#
# Copyright (c) 2017 Ricardo Garcia Silva
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================
#
#  docker build --squash -t pycsw . --no-cache
#
FROM alpine:latest

# There's bug in libxml2 v2.9.4 that prevents using an XMLParser with a schema
# file.
#
# https://bugzilla.gnome.org/show_bug.cgi?id=766834
#
# It seems to have been fixed upstream, but the fix has not been released into
# a new libxml2 version. As a workaround, we are sticking with the previous
# version, which works fine.
# This means that we need to use alpine's archives for version 3.1, which are
# the ones that contain the previous version of libxml2
#
# Also, for some unkwnon reason, alpine 3.1 version of libxml2 depends on
# python2. We'd rather use python3 for pycsw, so we install it too.
RUN echo 'http://dl-cdn.alpinelinux.org/alpine/v3.11/main' >> /etc/apk/repositories \
  && apk add --no-cache \
    ca-certificates \
    python3 \
    libpq \
    libxml2 \
    libxml2-dev \
    libxslt-dev \
    wget \
    postgresql-dev \
  && apk add --no-cache \
    --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ \
    --allow-untrusted \
    geos \
    proj \
    proj-util \
    geos-dev \
    proj-dev \
    git

RUN apk add --no-cache --virtual .build-deps \
    build-base \
    python3-dev

#
RUN apk add --update bash

RUN adduser -D -u 1000 pycsw

WORKDIR /tmp/pycsw


RUN git clone https://github.com/geopython/pycsw.git \
    && cd pycsw \
    && pip3 install --upgrade pip setuptools \
    && pip3 install parmap \
    && pip3 install lxml \
    && pip3 install xmltodict \
    && pip3 install gunicorn \
    && pip3 install -r requirements.txt \
    && pip3 install -r requirements-standalone.txt \
    && pip3 install -r requirements-pg.txt \
    && python3 setup.py build \
    && python3 setup.py install \
    && cp default-sample.cfg default.cfg \
    && cp docker/entrypoint.py /usr/local/bin/entrypoint.py \
    && chmod a+x /usr/local/bin/entrypoint.py


ENV PYCSW_CONFIG=/etc/pycsw/pycsw.cfg

RUN pip3 install xmltodict
RUN pip3 install parmap

RUN mkdir -p /etc/pycsw \
  && mkdir /var/lib/pycsw \
  && chown pycsw:pycsw /var/lib/pycsw


ADD docker_test/pycsw.cfg ${PYCSW_CONFIG}


RUN apk del .build-deps

WORKDIR /home/pycsw

USER pycsw

EXPOSE 8000

ENTRYPOINT [\
  "python3", \
  "/usr/local/bin/entrypoint.py" \
]